import numpy as np

a = np.zeros(3)
print(a)
print(type(a))
a = np.ones(3)
print(a)
a1 = np.empty(3)
print(a1)
a = np.linspace(1, 10)
print(a)
a = np.linspace(1, 10, 2)
print(a)
a = np.array([1, 2, 3])
print(a)
a = np.random.randint(10, size=6)
print(a)
print(np.sin(np.pi/2))
print(np.cos(np.pi/2))
print(np.cos(0))

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.min(a))
print("min")
print(a.min())
print(np.max(a))
print("max")
print(a.max())
print(np.sort(a))
print(a.sort())
print(np.std(a))
print(np.sum(a))
print(a.sum())
print(np.average(a))
print(a.average())
print(np.mean(a))
print(a.mean())
print(a < 3)
print(a[a < 3])
